### ISSUE TITLE
Suggestion: Have a copy-pasteable command ready without needing to enter your username

### ISSUE THREAD

**Issue by Wendelstein7** [SquidDev/SwitchMarket#1]
On product pages, you need to type in your username and a bid, and after that a copy pasteable command appears (/pay something@switchmarket.kst 666).

How about making this copy pasteable command appear immediately without arguments? That saves us from typing more and makes the workflow of placing bids more efficient ;)

xoxo

**Comment by Lemmmy** [comment]
should be pretty simple - should it just display the minimum next bid?

**Comment by Wendelstein7** [comment]
Yeah, or by default a 10% increase to make bids a little faster than 1 kst each time

**Comment by Lemmmy** [comment]
we did add a minimum bid not long ago which gets higher when the last bid increases

**Comment by Wendelstein7** [comment]
Cool thanks!
