### ISSUE TITLE
Disallow outbidding yourself

### ISSUE THREAD

**Issue by BTCTaras** [SquidDev/SwitchMarket#2]
You can reveal the reserve price by placing hundreds of minimum bids until you reach it

**Comment by Wendelstein7** [comment]
Can outbidding yourself be enabled again perhaps?
I sometimes may like to more 'secure' a purchase by raising it's price before going away for longer periods of time. Also, self-outbidding can be circumvented extremely easily by first raising with a fake username, later bidding with another username. :)
