### ISSUE TITLE
Add "Minimum reserve" boolean to products

### ISSUE THREAD

**Issue by BTCTaras** [SquidDev/SwitchMarket#5]
When true, the reserve price should be visible if there are no bids, saying it is the minimum bid, and do not allow any bids that are less than that amount

**Comment by Lemmmy** [comment]
what does this mean?

**Comment by BTCTaras** [comment]
Say I want to sell something, and I don't care how long it takes, but I won't accept less than 1,000 KST under any circumstances

I set a minimum bid of 1,000 KST (which is a reserve price, but with this special boolean set to true)

The minimum bid is publicly displayed and bidders can not bid less than that (if this boolean is false, it acts the way a reserve price does now - confidential, and you can bid under it)

This means I can put a house up for sale, with a duration-after-first-bid set, and the auction won't end until it is certain to be sold, whereas a reserve price auction will end whether the item sells or not

**Comment by Lemmmy** [comment]
okay, as i was thinking. how do you want it to look in the UI? something like this crude mockup perhaps?

![](https://you.wouldnot.download/a-watchmaker.png)

**Comment by BTCTaras** [comment]
Like that, but make the price tag grayer, and say "Minimum bid", i think

**Comment by Lemmmy** [comment]
sure, and then the text below it can go too then

**Comment by BTCTaras** [comment]
right its not needed in this case
