### ISSUE TITLE
multiple pages - page 2 is empty

### ISSUE THREAD

**Issue by Wendelstein7** [SquidDev/SwitchMarket#6]
Little bug: A page 2 is dynamically generated when page 1 is full, but that does not mean it needs a secondary page. Currently, there are exactly enough product lists so that page 1 is considered full, so a page 2 is generated, but there are no products for page 2. This means, that page 2 is completely empty.

**Comment by Lemmmy** [comment]
actually, its probably accounting for sold products in the page listing

https://github.com/Lemmmy/SwitchMarket/blob/74349fb99664dd66346976b5ac709985f2589c57/routes/views/products.js#L11-L20

**Comment by Lemmmy** [comment]
thanks! i found this little snippet in a markdown file that wasnt on their official docs:
![](https://you.wouldnot.download/a-tear.png)

**Comment by Wendelstein7** [comment]
great, neat and quick fixing :)
